name: Entorno Seguro SSH

on: 
  workflow_dispatch: # Permite activar el proceso manualmente desde GitHub

jobs:
  secure-ssh:
    runs-on: ubuntu-latest

    steps:
    - name: Actualizar sistema e instalar utilidades básicas
      run: |
        sudo apt-get update
        sudo apt-get install -y curl wget git

    - name: Crear túnel SSH e Interfaz Web (Anti-Bloqueo)
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: true # Solo tú puedes entrar con tu llave SSH de GitHub
